version: '3.8'

name: transcendence
services:
  db:
    container_name: database
    image: postgres:15.3-alpine3.18
    restart: unless-stopped
    env_file: ./backend/sql/.env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backend/sql/insertions.sql:/docker-entrypoint-initdb.d/insertions.sql
    networks:
      - transcendence_network
  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - 5000:8080
    networks:
      - transcendence_network
    depends_on:
      db:
        condition: service_started
  backend:
    container_name: backend
    build: ./backend/.
    restart: unless-stopped
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
      - 3003:3003
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - transcendence_network
    depends_on:
      db:
        condition: service_started
  frontend:
    container_name: frontend
    build: ./frontend/.
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - transcendence_network

volumes:
  db-data:

networks:
  transcendence_network:
    name: transcendence_network
    driver: bridge